const config = {
  gifs: true,
  tasks: {
    cbtIce: true,
    icyHot: true,
    precum: true,
    buttplug: true,
    dominant: true,
    flicking: true,
    handsOff: true,
    headOnly: true,
    ballSlaps: true,
    bothHands: true,
    shaftOnly: true,
    breathPlay: true,
    randomBeat: true,
    rubNipples: true,
    scratching: true,
    toothpaste: true,
    clothespins: true,
    headPalming: true,
    nondominant: true,
    rubberBands: true,
    overhandGrip: true,
    squeezeBalls: true,
    bindCockBalls: true,
    doubleStrokes: true,
    gripChallenge: true,
    halvedStrokes: true,
    clusterStrokes: true,
    pickYourPoison: true,
    teasingStrokes: true,
    gripAdjustments: true,
    nipplesAndStroke: true,
    randomStrokeSpeed: true,
    accelerationCycles: true,
    redLightGreenLight: true,
  },
  videos: true,
  pictures: true,
  redditId: "puppies",
  edgeCooldown: 10,
  minimumEdges: 0,
  ruinCooldown: 20,
  edgeFrequency: 0,
  slideDuration: 10,
  advancedEdging: true,
  advancedOrgasm: true,
  maximumOrgasms: 1,
  actionFrequency: 5,
  loopShortVideos: false,
  maximumGameTime: 20,
  minimumGameTime: 5,
  deniedProbability: 0,
  finalOrgasmDenied: false,
  finalOrgasmRandom: false,
  finalOrgasmRuined: false,
  postOrgasmTorture: false,
  ruinedProbability: 0,
  allowedProbability: 100,
  defaultStrokeStyle: 0,
  fastestStrokeSpeed: 5,
  finalOrgasmAllowed: true,
  slowestStrokeSpeed: 0.25,
  initialGripStrength: 3,
  maximumRuinedOrgasms: 0,
  minimumRuinedOrgasms: 0,
  postOrgasmTortureMaximumTime: 90,
  postOrgasmTortureMinimumTime: 10,
};

exports.seed = async knex => {
  await knex.raw(`TRUNCATE TABLE game_config CASCADE`);

  await knex("game_config").insert([
    {
      id: "67b83078-6da8-4c25-9faf-999b9a217095",
      config,
      title: "Seed Game",
      profile_id: "uMa6fjxVsZn6YD7h8r2zOx7LgDWZuwrL@clients",
      is_public: true,
    },
    {
      id: "f6341bb2-8fe6-48fa-8dfe-3b178bdd5dd7",
      config,
      title: "Seed Game 2",
      profile_id: "uMa6fjxVsZn6YD7h8r2zOx7LgDWZuwrL@clients",
      is_public: true,
    },
  ]);

  await knex.raw(`TRUNCATE TABLE game_tag CASCADE`);
  await knex("game_tag").insert([
    {
      game_config_id: "67b83078-6da8-4c25-9faf-999b9a217095",
      tag_id: "seed",
    },
    {
      game_config_id: "f6341bb2-8fe6-48fa-8dfe-3b178bdd5dd7",
      tag_id: "seed",
    },
  ]);
};
